extensions: {}
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args:
- -hide-package=hashmap
modules:
  ClassyPrelude.Map:
    filename: classy-prelude/ClassyPrelude/Map.hs
  ClassyPrelude.Maybe:
    filename: classy-prelude/ClassyPrelude/Maybe.hs
  ClassyPrelude.UVector:
    filename: classy-prelude/ClassyPrelude/UVector.hs
  ClassyPrelude.Text:
    filename: classy-prelude/ClassyPrelude/Text.hs
  ClassyPrelude.Char:
    filename: classy-prelude/ClassyPrelude/Char.hs
  ClassyPrelude.ByteString:
    filename: classy-prelude/ClassyPrelude/ByteString.hs
  ClassyPrelude.FilePath:
    filename: classy-prelude/ClassyPrelude/FilePath.hs
  ClassyPrelude.LByteString:
    filename: classy-prelude/ClassyPrelude/LByteString.hs
  ClassyPrelude.HashSet:
    filename: classy-prelude/ClassyPrelude/HashSet.hs
  ClassyPrelude.HashMap:
    filename: classy-prelude/ClassyPrelude/HashMap.hs
  ClassyPrelude.Set:
    filename: classy-prelude/ClassyPrelude/Set.hs
  ClassyPrelude.Vector:
    filename: classy-prelude/ClassyPrelude/Vector.hs
  ClassyPrelude.Classes:
    filename: classy-prelude/ClassyPrelude/Classes.hs
  ClassyPrelude:
    filename: classy-prelude/ClassyPrelude.hs
  Main(classy-prelude/test/main.hs):
    filename: classy-prelude/test/main.hs
  ClassyPrelude.LText:
    filename: classy-prelude/ClassyPrelude/LText.hs
  ClassyPrelude.Sequence:
    filename: classy-prelude/ClassyPrelude/Sequence.hs
  ClassyPrelude.List:
    filename: classy-prelude/ClassyPrelude/List.hs
